# Python Data preprocessing - Code Examples

## 1.0 Identifying missing values in tabular data

In [2]:
import numpy as np
import pandas as pd
from io import StringIO

# Create dummy dataset for training
csv_data = \
'''A,B,C,D
 1.0, 2.0,3.0,4.0
 5.2, 6.0,,9.0
 6.0, 7.0,,10.3
 7.0, 8.0,9.0,11.0
 8.0, 9.0,,
 9.0,10.2,11.0,
15.0,11.0,,14.0
16.0,12.0,13.0,
17.5,13.0,,16.0
18.0,14.0,15.0,17.1
20.0,15.0,18.0,'''

df = pd.read_csv(StringIO(csv_data))
df

A     B     C     D
0    1.0   2.0   3.0   4.0
1    5.2   6.0   NaN   9.0
2    6.0   7.0   NaN  10.3
3    7.0   8.0   9.0  11.0
4    8.0   9.0   NaN   NaN
5    9.0  10.2  11.0   NaN
6   15.0  11.0   NaN  14.0
7   16.0  12.0  13.0   NaN
8   17.5  13.0   NaN  16.0
9   18.0  14.0  15.0  17.1
10  20.0  15.0  18.0   NaN

In [3]:
# get the overview of the dataset
df.describe()


A          B          C          D
count  11.000000  11.000000   6.000000   7.000000
mean   11.154545   9.745455  11.500000  11.628571
std     6.329512   3.851328   5.205766   4.508035
min     1.000000   2.000000   3.000000   4.000000
25%     6.500000   7.500000   9.500000   9.650000
50%     9.000000  10.200000  12.000000  11.000000
75%    16.750000  12.500000  14.500000  15.000000
max    20.000000  15.000000  18.000000  17.100000

In [4]:
# Find out number of missing values in the dataset
print(df.isnull())
df.isnull().sum()

        A      B      C      D
0   False  False  False  False
1   False  False   True  False
2   False  False   True  False
3   False  False  False  False
4   False  False   True   True
5   False  False  False   True
6   False  False   True  False
7   False  False  False   True
8   False  False   True  False
9   False  False  False  False
10  False  False  False   True


A    0
B    0
C    5
D    4
dtype: int64

In [5]:
# Find out the values that are in the numpy array to inform missing values
# (access the underlying NumPy array via the `values` attribute)
df.values

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5.2,  6. ,  nan,  9. ],
       [ 6. ,  7. ,  nan, 10.3],
       [ 7. ,  8. ,  9. , 11. ],
       [ 8. ,  9. ,  nan,  nan],
       [ 9. , 10.2, 11. ,  nan],
       [15. , 11. ,  nan, 14. ],
       [16. , 12. , 13. ,  nan],
       [17.5, 13. ,  nan, 16. ],
       [18. , 14. , 15. , 17.1],
       [20. , 15. , 18. ,  nan]])

## 2.0 Eliminating training samples or features with missing values

In [7]:
# Find out which rows don't have missing values
# because axis 0 = by row, axis 1 = by column
# these basically show only rows that dont have any NaNs
print(df)
print(df.dropna(axis=0))

       A     B     C     D
0    1.0   2.0   3.0   4.0
1    5.2   6.0   NaN   9.0
2    6.0   7.0   NaN  10.3
3    7.0   8.0   9.0  11.0
4    8.0   9.0   NaN   NaN
5    9.0  10.2  11.0   NaN
6   15.0  11.0   NaN  14.0
7   16.0  12.0  13.0   NaN
8   17.5  13.0   NaN  16.0
9   18.0  14.0  15.0  17.1
10  20.0  15.0  18.0   NaN
      A     B     C     D
0   1.0   2.0   3.0   4.0
3   7.0   8.0   9.0  11.0
9  18.0  14.0  15.0  17.1


In [8]:
# Find out which columns don't have missing values
print(df.dropna(axis=1, how="any"))

       A     B
0    1.0   2.0
1    5.2   6.0
2    6.0   7.0
3    7.0   8.0
4    8.0   9.0
5    9.0  10.2
6   15.0  11.0
7   16.0  12.0
8   17.5  13.0
9   18.0  14.0
10  20.0  15.0


In [9]:
# How to drop rows where all columns are NaN
# because current data does not have a row with only NaN values,
# i will first add a new row of data with just NaN values
import copy

length = 4
# create an array of NaNs
nan_array = np.full(length, np.nan)
# create deep copy of existing df to not mess up it
df2 = copy.deepcopy(df)
# use loc to add a rows of NaN
df2.loc[-1] = nan_array
df2.index = df2.index + 1
df2 = df2.sort_index()
df2.loc[len(df2) + 1] = nan_array
df2.index = df2.index + 1
df2 = df2.sort_index()
print(df2)
print()

# now print again df2, drop all rows of only NaN
print(df2.dropna(axis=0, how="all"))

       A     B     C     D
1    NaN   NaN   NaN   NaN
2    1.0   2.0   3.0   4.0
3    5.2   6.0   NaN   9.0
4    6.0   7.0   NaN  10.3
5    7.0   8.0   9.0  11.0
6    8.0   9.0   NaN   NaN
7    9.0  10.2  11.0   NaN
8   15.0  11.0   NaN  14.0
9   16.0  12.0  13.0   NaN
10  17.5  13.0   NaN  16.0
11  18.0  14.0  15.0  17.1
12  20.0  15.0  18.0   NaN
14   NaN   NaN   NaN   NaN

       A     B     C     D
2    1.0   2.0   3.0   4.0
3    5.2   6.0   NaN   9.0
4    6.0   7.0   NaN  10.3
5    7.0   8.0   9.0  11.0
6    8.0   9.0   NaN   NaN
7    9.0  10.2  11.0   NaN
8   15.0  11.0   NaN  14.0
9   16.0  12.0  13.0   NaN
10  17.5  13.0   NaN  16.0
11  18.0  14.0  15.0  17.1
12  20.0  15.0  18.0   NaN


In [11]:
# drop rows that have fewer than 3 real values 
print(df)
print()

print(df.dropna(thresh=3))


       A     B     C     D
0    1.0   2.0   3.0   4.0
1    5.2   6.0   NaN   9.0
2    6.0   7.0   NaN  10.3
3    7.0   8.0   9.0  11.0
4    8.0   9.0   NaN   NaN
5    9.0  10.2  11.0   NaN
6   15.0  11.0   NaN  14.0
7   16.0  12.0  13.0   NaN
8   17.5  13.0   NaN  16.0
9   18.0  14.0  15.0  17.1
10  20.0  15.0  18.0   NaN

       A     B     C     D
0    1.0   2.0   3.0   4.0
1    5.2   6.0   NaN   9.0
2    6.0   7.0   NaN  10.3
3    7.0   8.0   9.0  11.0
5    9.0  10.2  11.0   NaN
6   15.0  11.0   NaN  14.0
7   16.0  12.0  13.0   NaN
8   17.5  13.0   NaN  16.0
9   18.0  14.0  15.0  17.1
10  20.0  15.0  18.0   NaN


In [12]:
# only drop rows where NaN appear in specific columns (here: 'D')
print(df.dropna(axis=0, subset=["D"], how="any"))

      A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.2   6.0   NaN   9.0
2   6.0   7.0   NaN  10.3
3   7.0   8.0   9.0  11.0
6  15.0  11.0   NaN  14.0
8  17.5  13.0   NaN  16.0
9  18.0  14.0  15.0  17.1


## 3.0 Imputing missing values

In [13]:
# again: original array
df.values

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5.2,  6. ,  nan,  9. ],
       [ 6. ,  7. ,  nan, 10.3],
       [ 7. ,  8. ,  9. , 11. ],
       [ 8. ,  9. ,  nan,  nan],
       [ 9. , 10.2, 11. ,  nan],
       [15. , 11. ,  nan, 14. ],
       [16. , 12. , 13. ,  nan],
       [17.5, 13. ,  nan, 16. ],
       [18. , 14. , 15. , 17.1],
       [20. , 15. , 18. ,  nan]])

In [15]:
# Find out column stats
print(df.mean())
print()
print(df.median())


A    11.154545
B     9.745455
C    11.500000
D    11.628571
dtype: float64

A     9.0
B    10.2
C    12.0
D    11.0
dtype: float64


In [17]:
# impute missing values via the column mean
# so replace the not a number values with mean
from sklearn.impute import SimpleImputer

print(df.values); print()
imr_mean = SimpleImputer(missing_values=np.nan, strategy="mean")
imr_mean.fit(df.values)
print(imr_mean); print()
mean_inputed_data = imr_mean.transform(df.values)
print(mean_inputed_data)

[[ 1.   2.   3.   4. ]
 [ 5.2  6.   nan  9. ]
 [ 6.   7.   nan 10.3]
 [ 7.   8.   9.  11. ]
 [ 8.   9.   nan  nan]
 [ 9.  10.2 11.   nan]
 [15.  11.   nan 14. ]
 [16.  12.  13.   nan]
 [17.5 13.   nan 16. ]
 [18.  14.  15.  17.1]
 [20.  15.  18.   nan]]

SimpleImputer()

[[ 1.          2.          3.          4.        ]
 [ 5.2         6.         11.5         9.        ]
 [ 6.          7.         11.5        10.3       ]
 [ 7.          8.          9.         11.        ]
 [ 8.          9.         11.5        11.62857143]
 [ 9.         10.2        11.         11.62857143]
 [15.         11.         11.5        14.        ]
 [16.         12.         13.         11.62857143]
 [17.5        13.         11.5        16.        ]
 [18.         14.         15.         17.1       ]
 [20.         15.         18.         11.62857143]]


In [18]:
# impute missing values via the column median
print(df.values); print()
imr_median = SimpleImputer(missing_values=np.nan, strategy="median")
imr_median.fit(df.values)
median_inputed_data = imr_median.transform(df.values)
print(median_inputed_data)


[[ 1.   2.   3.   4. ]
 [ 5.2  6.   nan  9. ]
 [ 6.   7.   nan 10.3]
 [ 7.   8.   9.  11. ]
 [ 8.   9.   nan  nan]
 [ 9.  10.2 11.   nan]
 [15.  11.   nan 14. ]
 [16.  12.  13.   nan]
 [17.5 13.   nan 16. ]
 [18.  14.  15.  17.1]
 [20.  15.  18.   nan]]

[[ 1.   2.   3.   4. ]
 [ 5.2  6.  12.   9. ]
 [ 6.   7.  12.  10.3]
 [ 7.   8.   9.  11. ]
 [ 8.   9.  12.  11. ]
 [ 9.  10.2 11.  11. ]
 [15.  11.  12.  14. ]
 [16.  12.  13.  11. ]
 [17.5 13.  12.  16. ]
 [18.  14.  15.  17.1]
 [20.  15.  18.  11. ]]


In [20]:
# impute missing values using LOCF
print(df2.values); print()
df3 = df2.ffill(inplace = False)
print(df3.values)


[[ nan  nan  nan  nan]
 [ 1.   2.   3.   4. ]
 [ 5.2  6.   nan  9. ]
 [ 6.   7.   nan 10.3]
 [ 7.   8.   9.  11. ]
 [ 8.   9.   nan  nan]
 [ 9.  10.2 11.   nan]
 [15.  11.   nan 14. ]
 [16.  12.  13.   nan]
 [17.5 13.   nan 16. ]
 [18.  14.  15.  17.1]
 [20.  15.  18.   nan]
 [ nan  nan  nan  nan]]

[[ nan  nan  nan  nan]
 [ 1.   2.   3.   4. ]
 [ 5.2  6.   3.   9. ]
 [ 6.   7.   3.  10.3]
 [ 7.   8.   9.  11. ]
 [ 8.   9.   9.  11. ]
 [ 9.  10.2 11.  11. ]
 [15.  11.  11.  14. ]
 [16.  12.  13.  14. ]
 [17.5 13.  13.  16. ]
 [18.  14.  15.  17.1]
 [20.  15.  18.  17.1]
 [20.  15.  18.  17.1]]


In [21]:
# impute missing values using NOCB
print(df2.values); print()
df3 = df2.bfill(inplace = False)
print(df3.values)

[[ nan  nan  nan  nan]
 [ 1.   2.   3.   4. ]
 [ 5.2  6.   nan  9. ]
 [ 6.   7.   nan 10.3]
 [ 7.   8.   9.  11. ]
 [ 8.   9.   nan  nan]
 [ 9.  10.2 11.   nan]
 [15.  11.   nan 14. ]
 [16.  12.  13.   nan]
 [17.5 13.   nan 16. ]
 [18.  14.  15.  17.1]
 [20.  15.  18.   nan]
 [ nan  nan  nan  nan]]

[[ 1.   2.   3.   4. ]
 [ 1.   2.   3.   4. ]
 [ 5.2  6.   9.   9. ]
 [ 6.   7.   9.  10.3]
 [ 7.   8.   9.  11. ]
 [ 8.   9.  11.  14. ]
 [ 9.  10.2 11.  14. ]
 [15.  11.  13.  14. ]
 [16.  12.  13.  16. ]
 [17.5 13.  15.  16. ]
 [18.  14.  15.  17.1]
 [20.  15.  18.   nan]
 [ nan  nan  nan  nan]]


## 4.0 Handling categorical data

### 4.1. Nominal and ordinal features

In [23]:
# create dummy dataset for categorial data
df = pd.DataFrame([['green', 'M', 10.1, 'sweatshirt'],
                   ['red',   'L', 13.5, 't-shirt'],
                   ['white', 'S', 13.5, 't-shirt'],
                   ['yellow','M', 13.5, 'sweatshirt'],
                   ['pink',  'M', 13.5, 'sweatshirt'],
                   ['black', 'S', 13.5, 't-shirt'],
                   ['grey',  'S', 13.5, 't-shirt'],
                   ['grey',  'S', 13.5, 'pullover'],
                   ['grey',  'L', 13.5, 't-shirt'],
                   ['orange','M', 13.5, 'pullover'],
                   ['lila',  'L', 13.5, 'pullover'],
                   ['blue', 'XL', 15.3, 'pullover']])

df.columns = ['color', 'sizeletter', 'price', 'classlabel']
print(df)

     color sizeletter  price  classlabel
0    green          M   10.1  sweatshirt
1      red          L   13.5     t-shirt
2    white          S   13.5     t-shirt
3   yellow          M   13.5  sweatshirt
4     pink          M   13.5  sweatshirt
5    black          S   13.5     t-shirt
6     grey          S   13.5     t-shirt
7     grey          S   13.5    pullover
8     grey          L   13.5     t-shirt
9   orange          M   13.5    pullover
10    lila          L   13.5    pullover
11    blue         XL   15.3    pullover


In [23]:
# Find out different categories in the dataset
# color and classlabel are nominal, sizeletter is ordinal category
# this assessment must be done manually as far as i know

### 4.2. Mapping ordinal features

In [24]:
# first save the ordinal category size_code into df
# define mapping dictionary S=1, M=2, L=3 and XL=4 and add size_code column to the dataset
size_mapping = {'XL': 4,
                'L': 3,
                'M': 2,
                'S': 1}
df["size_code"] = df["sizeletter"].map(size_mapping)

# next save the nominal categories color_code and label_code into df
df["color_code"] = df.color.astype("category").cat.codes
df["label_code"] = df.classlabel.astype("category").cat.codes
print(df)




     color sizeletter  price  classlabel  size_code  color_code  label_code
0    green          M   10.1  sweatshirt          2           2           1
1      red          L   13.5     t-shirt          3           7           2
2    white          S   13.5     t-shirt          1           8           2
3   yellow          M   13.5  sweatshirt          2           9           1
4     pink          M   13.5  sweatshirt          2           6           1
5    black          S   13.5     t-shirt          1           0           2
6     grey          S   13.5     t-shirt          1           3           2
7     grey          S   13.5    pullover          1           3           0
8     grey          L   13.5     t-shirt          3           3           2
9   orange          M   13.5    pullover          2           5           0
10    lila          L   13.5    pullover          3           4           0
11    blue         XL   15.3    pullover          4           1           0


In [25]:
# define inverse mapping function
# idea is to create a python dictionary, where every number equals a size
print(size_mapping.items())
inv_size_mapping = {value: key for key, value in size_mapping.items()}
print(inv_size_mapping.items())
df['size_code'].map(inv_size_mapping)

dict_items([('XL', 4), ('L', 3), ('M', 2), ('S', 1)])
dict_items([(4, 'XL'), (3, 'L'), (2, 'M'), (1, 'S')])


0      M
1      L
2      S
3      M
4      M
5      S
6      S
7      S
8      L
9      M
10     L
11    XL
Name: size_code, dtype: object

In [26]:
# Find out inv size mapping dictionary
print(size_mapping.items())
print(inv_size_mapping.items())

dict_items([('XL', 4), ('L', 3), ('M', 2), ('S', 1)])
dict_items([(4, 'XL'), (3, 'L'), (2, 'M'), (1, 'S')])


### 4.3. Encoding class labels

In [ ]:
from sklearn.preprocessing import LabelEncoder
import copy

# u need a separate encoder for each category
color_encoder = LabelEncoder()
label_encoder = LabelEncoder()

# Label encoding with sklearn's LabelEncoder
# first take a deepcopy of dataframe
df2 = copy.deepcopy(df)
#print(df2)
# remove 2 columns and recreate them with sklearn library
df2 = df2.drop(labels=["color_code", "label_code"], axis=1)
print(df2); print(); print()

# fit_transform combines fit and transform phases
# fit phase encoder learns how data looks from categorical labels point of view
# transform phase it creates an array of equivalent numbers to categories
df2["color_code"] = color_encoder.fit_transform(df2['color'])
df2["label_code"] = label_encoder.fit_transform(df2["classlabel"])
print(df2)


     color sizeletter  price  classlabel  size_code
0    green          M   10.1  sweatshirt          2
1      red          L   13.5     t-shirt          3
2    white          S   13.5     t-shirt          1
3   yellow          M   13.5  sweatshirt          2
4     pink          M   13.5  sweatshirt          2
5    black          S   13.5     t-shirt          1
6     grey          S   13.5     t-shirt          1
7     grey          S   13.5    pullover          1
8     grey          L   13.5     t-shirt          3
9   orange          M   13.5    pullover          2
10    lila          L   13.5    pullover          3
11    blue         XL   15.3    pullover          4


     color sizeletter  price  classlabel  size_code  color_code  label_code
0    green          M   10.1  sweatshirt          2           2           1
1      red          L   13.5     t-shirt          3           7           2
2    white          S   13.5     t-shirt          1           8           2
3   yellow        

In [31]:
# reverse mapping
# now that label encoder has been used, we can use its 
# inverse_transform function to easily revert code numbers to equivalent category keys

print(f"colors of data: {color_encoder.inverse_transform(df2["color_code"])}")
print(f"label classes of data: {label_encoder.inverse_transform(df2["label_code"])}")

colors of data: ['green' 'red' 'white' 'yellow' 'pink' 'black' 'grey' 'grey' 'grey'
 'orange' 'lila' 'blue']
label classes of data: ['sweatshirt' 't-shirt' 't-shirt' 'sweatshirt' 'sweatshirt' 't-shirt'
 't-shirt' 'pullover' 't-shirt' 'pullover' 'pullover' 'pullover']


### 4.4. Performing one-hot encoding on nominal features

In [32]:
# encode the color column using LabelEncoder

# i think i alrdy did this...
print(df2["color_code"])


0     2
1     7
2     8
3     9
4     6
5     0
6     3
7     3
8     3
9     5
10    4
11    1
Name: color_code, dtype: int32


In [42]:
# One hot encode the color column
# one hot encoding means, each category has its own column
# and then, 1 means something is that color
from sklearn.preprocessing import OneHotEncoder

ohe_colors = OneHotEncoder()

X = df2[['color', 'sizeletter', 'price']].values
print(X); print()
print(X[0])

# encoded_colors = ohe_colors.fit_transform(X[["color"]]).toarray()
# print(encoded_colors)

#encoded_df2 = df2

[['green' 'M' 10.1]
 ['red' 'L' 13.5]
 ['white' 'S' 13.5]
 ['yellow' 'M' 13.5]
 ['pink' 'M' 13.5]
 ['black' 'S' 13.5]
 ['grey' 'S' 13.5]
 ['grey' 'S' 13.5]
 ['grey' 'L' 13.5]
 ['orange' 'M' 13.5]
 ['lila' 'L' 13.5]
 ['blue' 'XL' 15.3]]

['green' 'M' 10.1]


In [ ]:
# one-hot encoding via pandas get_dummies


In [ ]:
# multicollinearity guard in get_dummies
# Multicollinearity arises when two or more variables in a regression are highly correlated
# removes the 1st categorial value (black is now a row with all the other colors as zero)
# (Note! dropping the first dummy variable can also lead to a slight loss in interpretability, 
# as you'll have to infer the dropped category based on the values of the remaining columns.)


## 5.0 Partitioning a dataset into a seperate training and test set

In [ ]:
# Read the wine dataset
# https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data
# df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)

# if the Wine dataset is temporarily unavailable from the
# UCI machine learning repository, un-comment the following line
# of code to load the dataset from a local path:

# df_wine = pd.read_csv('wine.data', header=None)

df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.head()

In [ ]:
# get wine dataset overview


In [ ]:
# find out unique classes


In [ ]:
# Create training and test datasets (ensure that distributions are preserved)
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test = train_test_split(X, y, 
    test_size=0.3, random_state=0, stratify=y)
print("Shapes: {} = {} + {}".format(X.shape, X_train.shape, X_test.shape))

## 6.0 Bringing features onto the same scale

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [ ]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

## 7.0 Selecting meaningful features

Assessing feature importance with Random Forests

In [ ]:
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

feat_labels = df_wine.columns[1:]
forest = RandomForestClassifier(n_estimators=10000, random_state=0, n_jobs=-1)

forest.fit(X_train, y_train)
importances = forest.feature_importances_

indices = np.argsort(importances)[::-1]

for f in range(X_train.shape[1]):
    print("%2d) %-*s %f" % (f + 1, 30, 
                            feat_labels[indices[f]], 
                            importances[indices[f]]))

plt.title('Feature Importance')
plt.bar(range(X_train.shape[1]), 
        importances[indices],
        align='center')

plt.xticks(range(X_train.shape[1]), 
           feat_labels[indices], rotation=90)
plt.xlim([-1, X_train.shape[1]])
plt.tight_layout()
#plt.savefig('images/04_09.png', dpi=300)
plt.show()

In [ ]:
from sklearn.feature_selection import SelectFromModel

sfm = SelectFromModel(forest, threshold=0.1, prefit=True)
X_selected = sfm.transform(X_train)
print('Number of features that meet this threshold criterion:', 
      X_selected.shape[1])

Print the 3 features that met the threshold criterion for feature selection that was set earlier 

In [ ]:
for f in range(X_selected.shape[1]):
    print("%2d) %-*s %f" % (f + 1, 30, 
                            feat_labels[indices[f]], 
                            importances[indices[f]]))